name: md to docx

on:
  push:
    branches: 
      - master

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gitconfig
        run: |
          git config --local user.email "info@daco.dev"
          git config --local user.name "5ym"
      - name: diff hit and init branch
        continue-on-error: true
        run: |
          git fetch --no-tags --prune --depth=1
          git checkout docx || (git checkout --orphan docx && \
            git rm -rf . && git commit --allow-empty -m "first commit" && git checkout master && \
            find -name "*.md" | sed s/.md$// >> modified.txt ; exit 1)
          cat convertdone.txt | { read v; git diff --name-only --diff-filter=MAR $v master | grep .md$ | sed s/.md$// >> modified.txt; }
          cat convertdone.txt | { read v; git diff --name-only --diff-filter=D $v master | grep .md$ | sed s/.md$// | { read f; rm -f $f.docx; }; }
          git checkout master
      - name: lint file and save hash
        run: |
          yarn global add markdownlint-cli2
          cat modified.txt && cat modified.txt | xargs `yarn global bin`/markdownlint-cli2
          echo $GITHUB_SHA > convertdone.txt
          git add convertdone.txt
      - name: convert file
        uses: docker://pandoc/core
        with:
          entrypoint: sh
          args: -c "cat modified.txt | xargs -i pandoc -o {}.docx {}.md"
      - name: change add and push
        run: |
          git add **/*.docx && git commit -m "tmp"
          git checkout docx && git checkout master **/*.docx
          git add . && git commit -m "convert"
          git push origin HEAD
