name: md to docx

on:
  push:
    branches: 
      - master

jobs:
  convert:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core
        with:
          entrypoint: sh
          args: -c 'find -name *.md | sed -e 's/.md$//' | { read v; pandoc -o $v.docx $v.md; }'
      - name: git checkout
        run: |
          git config --local user.email "info@daco.dev"
          git config --local user.name "5ym"
          git checkout docx || git checkout -b docx
          git commit -m "Convert docx" -a
          git push origin HEAD
