name: md to docx

on:
  push:
    branches: 
      - master

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git config and fetch branch
        run: |
          git config --local user.email "info@daco.dev"
          git config --local user.name "5ym"
          git config --global core.quotepath false
          git fetch --no-tags --prune --depth=1
      - name: check branch exists and init
        continue-on-error: true
        run: |
          git checkout docx || (git checkout --orphan docx && \
            git rm -rf . && git commit --allow-empty -m "first commit" && \
            echo 4b825dc642cb6eb9a060e54bf8d69288fbee4904 > convertdone.txt)
      - name: check diff and lint
        run: |
          git diff --name-only --diff-filter=MAR `cat convertdone.txt` master | grep .md$ | sed s/.md$// >> modified.txt
          git diff --name-only --diff-filter=D `cat convertdone.txt` master | grep .md$ | sed s/.md$// | { read f; rm -f $f.docx; }
          git checkout master
          yarn global add markdownlint-cli2
          cat modified.txt && cat modified.txt | xargs `yarn global bin`/markdownlint-cli2
      - name: convert file
        uses: docker://pandoc/core
        with:
          entrypoint: sh
          args: -c "cat modified.txt | xargs -i pandoc -o {}.docx {}.md"
      - name: save hash and change add and push
        run: |
          git add . && git commit -m "tmp"
          git checkout docx
          git show master:modified.txt | xargs -i git checkout master {}.docx
          echo $GITHUB_SHA > convertdone.txt
          git add . && git commit -m "convert"
          git push origin HEAD
