name: md to pdf

on:
  push:
    branches: 
      - master

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git config and fetch branch
        run: |
          git config --local user.email "info@daco.dev"
          git config --local user.name "5ym"
          git config --global core.quotepath false
          git fetch --no-tags --prune --depth=1
      - name: check branch exists and init and remove file
        continue-on-error: true
        run: |
          (git checkout pdf && git fetch --unshallow origin pdf) || \
            (git checkout --orphan pdf && \
            git rm -rf . && echo 4b825dc642cb6eb9a060e54bf8d69288fbee4904 > convertdone.txt && \
            git add . && git commit -m "first commit")
          set -o pipefail
          git diff --name-only --diff-filter=D `git show pdf:convertdone.txt` master | grep .md$ | sed s/.md$// | { read f; rm -f $f.pdf; } && \
          git add . && git commit -m "remove"
      - name: check diff and check modified
        continue-on-error: true
        id: modify
        run: |
          set -o pipefail
          git diff --name-only --diff-filter=MAR `git show pdf:convertdone.txt` master | grep .md$ | sed s/.md$// >> modified.txt && \
          echo "::set-output name=status::success"
      - name: lint
        if: steps.modify.outputs.status == 'success'
        run: |
          git checkout master
          git checkout -b tmp
          yarn global add markdownlint-cli2
          cat modified.txt | xargs `yarn global bin`/markdownlint-cli2
      - name: convert file
        if: steps.modify.outputs.status == 'success'
        uses: docker://pandoc/core
        with:
          entrypoint: sh
          args: -c "cat modified.txt | xargs -i pandoc -o {}.pdf {}.md"
      - name: save hash and change add
        if: steps.modify.outputs.status == 'success'
        run: |
          git add . && git commit -m "tmp"
          git checkout pdf
          git show tmp:modified.txt | xargs -i git checkout tmp {}.pdf
          echo $GITHUB_SHA > convertdone.txt
          git add . && git commit -m "convert"
      - name: push
        run: git push origin HEAD
