name: md to pdf

on:
  push:
    branches: 
      - master

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git config and fetch branch
        run: |
          git config --local user.email "info@daco.dev"
          git config --local user.name "5ym"
          git config --global core.quotepath false
          git fetch --no-tags --prune --depth=1
      - name: check branch exists and init and remove file and check modify
        id: check
        continue-on-error: true
        run: |
          (git checkout pdf && git fetch --unshallow origin pdf) || \
            (git checkout --orphan pdf && \
            git rm -rf . && echo 4b825dc642cb6eb9a060e54bf8d69288fbee4904 > convertdone.txt && \
            git add . && git commit -m "first commit")
          set -o pipefail
          git diff --name-only --diff-filter=D `git show pdf:convertdone.txt` master | grep .md$ | sed s/.md$// | { read f; rm -f $f.pdf; } && \
          git add . && git commit -m "remove"
          git diff --name-only --diff-filter=MAR `git show pdf:convertdone.txt` master | grep .md$ | sed s/.md$// >> modified.txt && \
          echo "::set-output name=status::success"
      - name: lint and convert and push
        if: steps.check.outputs.status == 'success'
        run: |
          git checkout master
          git checkout -b tmp
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker run -v $PWD:/data --entrypoint sh ghcr.io/5ym/pandoc -c "cat modified.txt | xargs markdownlint-cli2 && \
            cat modified.txt | xargs -i pandoc --template eisvogel --listings --pdf-engine xelatex -V CJKmainfont='Noto Serif CJK JP' -o {}.pdf {}.md"
          git add . && git commit -m "tmp"
          git checkout pdf
          git show tmp:modified.txt | xargs -i git checkout tmp {}.pdf
          echo $GITHUB_SHA > convertdone.txt
          git add . && git commit -m "convert"
      - name: push
        run: git push origin HEAD
