name: qd to pdf

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: 5ym/paper@v1
