name: md to docx

on:
  push:
    branches: 
      - master

jobs:
  convert:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: output diff file
        continue-on-error: true
        run: |
          git checkout docx || (git checkout -b docx && find -name *.md | sed s/.md$// >> modified.txt && exit)
          git merge master
          cat convertdone.txt | { read v; git diff --name-only --diff-filter=MA $v master | grep .md$ | sed s/.md$// >> modified.txt; }
          cat convertdone.txt | { read v; git diff --name-only --diff-filter=D $v master | grep .md$ | sed s/.md$// | { read f; rm -f $v.docx; }; }
      - uses: docker://pandoc/core
        with:
          entrypoint: sh
          args: -c "cat modified.txt | { read v; pandoc -o $v.docx $v.md; echo $v; }"
      - name: save hash and remove diff
        run: |
          echo $GITHUB_SHA > convertdone.txt
          rm -f modified.txt
      - name: git checkout
        run: |
          git config --local user.email "info@daco.dev"
          git config --local user.name "5ym"
          git add .
          git commit -m "Convert docx"
          git push origin HEAD
