name: md to docx

on:
  push:
    branches: 
      - master

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git config and fetch branch
        run: |
          git config --local user.email "info@daco.dev"
          git config --local user.name "5ym"
          git config --global core.quotepath false
          git fetch --no-tags --prune --depth=1
      - name: check branch exists and init and remove file
        continue-on-error: true
        run: |
          (git checkout docx && git fetch --unshallow origin docx) || \
            (git checkout --orphan docx && \
            git rm -rf . && echo 4b825dc642cb6eb9a060e54bf8d69288fbee4904 > convertdone.txt && \
            git add . && git commit -m "first commit")
          set -o pipefail
          git diff --name-only --diff-filter=D `git show docx:convertdone.txt` master | grep .md$ | sed s/.md$// | { read f; rm -f $f.docx; } && \
          git add . && git commit -m "remove"
      - name: check diff
        run: git diff --name-only --diff-filter=MAR `git show docx:convertdone.txt` master | grep .md$ | sed s/.md$// >> modified.txt
      - name: lint
        run: |
          cat modified.txt
          git checkout master
          git checkout -b tmp
          yarn global add markdownlint-cli2
          cat modified.txt | xargs `yarn global bin`/markdownlint-cli2
      - name: convert file
        uses: docker://pandoc/core
        with:
          entrypoint: sh
          args: -c "cat modified.txt | xargs -i pandoc -o {}.docx {}.md"
      - name: save hash and change add and push
        run: |
          git add . && git commit -m "tmp"
          git checkout docx
          git show tmp:modified.txt | xargs -i git checkout tmp {}.docx
          echo $GITHUB_SHA > convertdone.txt
          git add . && git commit -m "convert"
          git push origin HEAD
